if(TARGET modules)
  find_package(hiredis CONFIG QUIET)
  if(hiredis_FOUND)
    # RelWithDebInfo has no dedicated hiredis import config; map it to Release so we
    # link the /MD release static lib (not the /MDd debug one). Scoped to hiredis only.
    if(TARGET hiredis::hiredis)
      set_target_properties(hiredis::hiredis PROPERTIES MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release)
    endif()
    target_link_libraries(modules PRIVATE hiredis::hiredis)
    target_compile_definitions(modules PRIVATE DAD_TELEMETRY_AVAILABLE)
    execute_process(COMMAND git -C ${CMAKE_CURRENT_LIST_DIR}/../mod-playerbots rev-parse --short HEAD
                    OUTPUT_VARIABLE DAD_FORK_SHA OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(NOT DAD_FORK_SHA)
      set(DAD_FORK_SHA "unknown")
    endif()
    target_compile_definitions(modules PRIVATE DAD_FORK_SHA="${DAD_FORK_SHA}")
    target_include_directories(modules PRIVATE ${CMAKE_CURRENT_LIST_DIR}/src)
    if(WIN32)
      target_link_libraries(modules PRIVATE ws2_32)
    endif()
  else()
    message(WARNING "[mod-telemetry-redis] hiredis not found - telemetry disabled")
  endif()
endif()
